apiVersion: v1
kind: List
metadata:
resourceVersion: ""
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: ${NAMESPACE}
    name: ${DEPLOYMENT}
    labels:
      app: ${APP}
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: ${APP}
    template:
      metadata:
        labels:
          app: ${APP}
      spec:
        containers:
        - name: ${APP}
          image: ${IMAGE}
          env:
            - name: RELEASE_VERSION
              value: "${RELEASE_VERSION}"
            - name: DT_GRAIL_QUERY_BUDGET_GB
              value: "${DT_GRAIL_QUERY_BUDGET_GB}"
            - name: DT_MCP_DISABLE_TELEMETRY
              value: "${DT_MCP_DISABLE_TELEMETRY}"
            - name: DT_MCP_TELEMETRY_APPLICATION_ID
              value: "${DT_MCP_TELEMETRY_APPLICATION_ID}"
            - name: DT_MCP_TELEMETRY_ENDPOINT_URL
              value: "${DT_MCP_TELEMETRY_ENDPOINT_URL}"
            - name: DT_MCP_TELEMETRY_DEVICE_ID
              value: "${DT_MCP_TELEMETRY_DEVICE_ID}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
            - name: DT_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: dt-credentials
                  key: DT_ENVIRONMENT
            - name: DT_PLATFORM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dt-credentials
                  key: DT_PLATFORM_TOKEN
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: dt-credentials
                  key: OTEL_EXPORTER_OTLP_HEADERS
            - name: DT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dt-credentials
                  key: DT_API_TOKEN
          ports:
          - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP}
    name: ${DEPLOYMENT}-service
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    #  nodePort: 30303
    selector:
      app: ${APP}
    type: ClusterIP