apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: tacocorp-mcp-server-ingress
  namespace: tacocorp-mcp-server
spec:
  rules:
  - host: tacocorp-mcp-server.whydevslovedynatrace.com
    http:
      paths:
      - backend:
          service:
            name: dynatrace-mcp-server-service
            port:
              number: 8080
        path: /
        pathType: Prefix
  #tls:
  #- hosts:
  #  - tacocorp-mcp-server.whydevslovedynatrace.com
  #  secretName: tacocorp-mcp-server-tls